# Generated by Django 5.0.4 on 2024-04-11 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('asset_type', models.CharField(choices=[('equity', 'equity'), ('debt', 'debt'), ('gold', 'gold'), ('real_estate', 'real_estate')], max_length=20)),
                ('holding_type', models.CharField(choices=[('mutual_fund', 'mutual_fund'), ('stock', 'stock')], max_length=20)),
                ('current_price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=5)),
                ('price', models.DecimalField(decimal_places=10, max_digits=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_by', to='api.assets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
