# Generated by Django 5.0.4 on 2024-04-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assets_show_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='name',
            new_name='fetch_name',
        ),
    ]
