# Generated by Django 5.0.4 on 2024-04-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_assets_fetch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='fetch_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
