# Generated by Django 5.0.4 on 2024-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_assets_fetch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='holding_type',
            field=models.CharField(choices=[('mutual_fund', 'mutual_fund'), ('stock', 'stock'), ('etf', 'etf')], max_length=20),
        ),
    ]
